/* Plugin generated by AMXX-Studio */

#include <amxmodx>
#include <hamsandwich>
#define PLUGIN "Unload Metadrawer Fix"
#define VERSION "1.0"
#define AUTHOR "Toan"

public plugin_init()
{
	register_plugin(PLUGIN, VERSION, AUTHOR)	
}

public plugin_natives()
{
	register_native("md_zb_skill","do_nothing", 1)
	register_native("nav_set_special_ammo","do_nothing", 1)
	register_native("nav_reset_money","do_nothing", 1)
}

public do_nothing(){

}